import {CubicBezierCurve,
  CurvePath,
  LatheGeometry,
  LineCurve,
  Mesh,
  MeshPhysicalMaterial,
  QuadraticBezierCurve,
  Vector2} from 'three'
import type {BufferGeometry, Object3D} from 'three'
import {BOWL_CLEARCOAT,
  BOWL_CLEARCOAT_ROUGHNESS,
  BOWL_COLOR,
  BOWL_PROFILE_DIVISIONS,
  BOWL_RADIAL_SEGMENTS,
  BOWL_ROUGHNESS} from '@/scene/dimensions'

/**
 * The dice bowl: a turned wooden vessel, generated by revolving a profile
 * around the vertical axis.
 *
 * Straight sided rather than flared — the foot is nine tenths of the opening —
 * and flat bottomed, which is what a tray meant to be read from above wants to
 * be. A deeply curved base rolls every die back to the middle and stacks them
 * where they cannot be told apart; a flat one lets a throw spread out and lie
 * where it landed.
 *
 * The profile is a closed shell — up the inside, over the rim, down the
 * outside and back in under the foot — rather than a single open surface. An
 * open surface would be one sided, which shades wrongly at grazing angles and
 * casts a shadow with a hole in it.
 *
 * Its turned detail is the one place craft can show, because the geometry is
 * procedural and carries no sculpted detail: a bearing ring under the foot, a
 * wall that swells as it rises, and a bead rolled over the rim. All three are
 * what a bowl turned on a real lathe has, and they cost nothing but profile
 * points. The bead earns its keep twice over from directly above, where it is
 * the only thing left drawing the bowl's outline.
 */
export class Dish {
  private readonly bowl: Mesh // The single revolved shell
  private readonly geometry: LatheGeometry
  private readonly material: MeshPhysicalMaterial

  constructor() {
    this.geometry = new LatheGeometry(
      Dish.buildProfile(),
      BOWL_RADIAL_SEGMENTS,
    )

    // Lacquered wood: the gloss layer, not surface detail, describes the
    // curvature. There are no texture maps in this project and never will be,
    // so a material whose character comes from its coating rather than its
    // grain is the one that survives being untextured.
    this.material = new MeshPhysicalMaterial({
      color: BOWL_COLOR,
      roughness: BOWL_ROUGHNESS,
      metalness: 0,
      clearcoat: BOWL_CLEARCOAT,
      clearcoatRoughness: BOWL_CLEARCOAT_ROUGHNESS,
    })

    this.bowl = new Mesh(this.geometry, this.material)
    this.bowl.castShadow = true
    this.bowl.receiveShadow = true
  }

  get object(): Object3D {
    return this.bowl
  }

  /**
   * The revolved shell itself, exposed so the physics world can collide
   * against the very triangles the bowl is drawn from. There is then only one
   * description of the bowl's shape, and a die cannot hit a wall that is not
   * where it looks.
   */
  get shell(): BufferGeometry {
    return this.geometry
  }

  dispose(): void {
    this.geometry.dispose()
    this.material.dispose()
  }

  /**
   * Builds the cross-section that gets revolved into the bowl, as points of
   * (radius, height) with the table surface at height zero.
   *
   * Authored as curve segments rather than as a list of points so the sweeps
   * stay smooth while the foot stays crisp: straight runs are emitted as
   * single segments and only the curves are subdivided.
   *
   * Direction is load bearing. LatheGeometry takes each surface normal from
   * the profile's tangent turned a quarter turn, so traversing the shell the
   * other way round points every normal into the solid and the bowl renders
   * inside out. It has to run underside first and finish on the inside.
   * @returns The sampled profile, running from the centre of the underside
   *   round to the centre of the inside base
   */
  private static buildProfile(): Vector2[] {
    const profile = new CurvePath<Vector2>()

    // Underside: recessed, so the bowl sits on its ring and not on its belly
    profile.add(new QuadraticBezierCurve(
      new Vector2(0.00, 0.24),
      new Vector2(3.72, 0.24),
      new Vector2(4.02, 0.00),
    ))

    // Foot: the bearing ring, then a chamfer up off the table
    profile.add(new LineCurve(new Vector2(4.02, 0.00), new Vector2(4.40, 0.00)))
    profile.add(new LineCurve(new Vector2(4.40, 0.00), new Vector2(4.50, 0.03)))
    profile.add(new LineCurve(new Vector2(4.50, 0.03), new Vector2(4.70, 0.27)))

    // Outside wall: swells away from the foot, straightening toward the rim
    profile.add(new CubicBezierCurve(
      new Vector2(4.70, 0.27),
      new Vector2(5.02, 1.08),
      new Vector2(5.25, 2.33),
      new Vector2(5.25, 3.93),
    ))

    // Rim bead: rolled over the top, outside edge to inside edge
    profile.add(new CubicBezierCurve(
      new Vector2(5.25, 3.93),
      new Vector2(5.25, 4.29),
      new Vector2(4.89, 4.29),
      new Vector2(4.89, 3.93),
    ))

    // Inside wall: near vertical all the way down, easing off at the bottom
    profile.add(new CubicBezierCurve(
      new Vector2(4.89, 3.93),
      new Vector2(4.75, 2.55),
      new Vector2(4.62, 1.45),
      new Vector2(4.45, 0.90),
    ))

    // Fillet: turns the wall into the floor, tangent to both
    profile.add(new QuadraticBezierCurve(
      new Vector2(4.45, 0.90),
      new Vector2(4.34, 0.53),
      new Vector2(4.10, 0.53),
    ))

    // Inside base: flat, and a straight run rather than a curve so it is
    // genuinely flat and not merely flattening
    profile.add(new LineCurve(new Vector2(4.10, 0.53), new Vector2(0.00, 0.53)))

    return profile.getPoints(BOWL_PROFILE_DIVISIONS)
  }
}
