import {CubicBezierCurve,
  CurvePath,
  LatheGeometry,
  LineCurve,
  Mesh,
  MeshPhysicalMaterial,
  QuadraticBezierCurve,
  Vector2} from 'three'
import type {BufferGeometry, Object3D} from 'three'
import {BOWL_CLEARCOAT,
  BOWL_CLEARCOAT_ROUGHNESS,
  BOWL_COLOR,
  BOWL_PROFILE_DIVISIONS,
  BOWL_RADIAL_SEGMENTS,
  BOWL_ROUGHNESS} from '@/scene/dimensions'

/**
 * The dice bowl: a turned wooden vessel, generated by revolving a profile
 * around the vertical axis.
 *
 * The profile is a closed shell — up the inside, over the rim, down the
 * outside and back in under the foot — rather than a single open surface. An
 * open surface would be one sided, which shades wrongly at grazing angles and
 * casts a shadow with a hole in it.
 *
 * Its silhouette is the one place craft can show, because the geometry is
 * procedural and carries no sculpted detail: a bearing ring under the foot, an
 * S-curved wall, and a bead rolled over the rim. All three are what a bowl
 * turned on a real lathe has, and they cost nothing but profile points.
 */
export class Dish {
  private readonly bowl: Mesh // The single revolved shell
  private readonly geometry: LatheGeometry
  private readonly material: MeshPhysicalMaterial

  constructor() {
    this.geometry = new LatheGeometry(
      Dish.buildProfile(),
      BOWL_RADIAL_SEGMENTS,
    )

    // Lacquered wood: the gloss layer, not surface detail, describes the
    // curvature. There are no texture maps in this project and never will be,
    // so a material whose character comes from its coating rather than its
    // grain is the one that survives being untextured.
    this.material = new MeshPhysicalMaterial({
      color: BOWL_COLOR,
      roughness: BOWL_ROUGHNESS,
      metalness: 0,
      clearcoat: BOWL_CLEARCOAT,
      clearcoatRoughness: BOWL_CLEARCOAT_ROUGHNESS,
    })

    this.bowl = new Mesh(this.geometry, this.material)
    this.bowl.castShadow = true
    this.bowl.receiveShadow = true
  }

  get object(): Object3D {
    return this.bowl
  }

  /**
   * The revolved shell itself, exposed so the physics world can collide
   * against the very triangles the bowl is drawn from. There is then only one
   * description of the bowl's shape, and a die cannot hit a wall that is not
   * where it looks.
   */
  get shell(): BufferGeometry {
    return this.geometry
  }

  dispose(): void {
    this.geometry.dispose()
    this.material.dispose()
  }

  /**
   * Builds the cross-section that gets revolved into the bowl, as points of
   * (radius, height) with the table surface at height zero.
   *
   * Authored as curve segments rather than as a list of points so the sweeps
   * stay smooth while the foot stays crisp: straight runs are emitted as
   * single segments and only the curves are subdivided.
   *
   * Direction is load bearing. LatheGeometry takes each surface normal from
   * the profile's tangent turned a quarter turn, so traversing the shell the
   * other way round points every normal into the solid and the bowl renders
   * inside out. It has to run underside first and finish on the inside.
   * @returns The sampled profile, running from the centre of the underside
   *   round to the centre of the inside base
   */
  private static buildProfile(): Vector2[] {
    const profile = new CurvePath<Vector2>()

    // Underside: recessed, so the bowl sits on its ring and not on its belly
    profile.add(new QuadraticBezierCurve(
      new Vector2(0.00, 0.16),
      new Vector2(1.10, 0.16),
      new Vector2(1.30, 0.00),
    ))

    // Foot: the bearing ring, then a chamfer up off the table
    profile.add(new LineCurve(new Vector2(1.30, 0.00), new Vector2(1.55, 0.00)))
    profile.add(new LineCurve(new Vector2(1.55, 0.00), new Vector2(1.62, 0.02)))
    profile.add(new LineCurve(new Vector2(1.62, 0.02), new Vector2(1.75, 0.18)))

    // Outside wall: swells away from the foot, straightening toward the rim
    profile.add(new CubicBezierCurve(
      new Vector2(1.75, 0.18),
      new Vector2(2.75, 0.72),
      new Vector2(3.42, 1.55),
      new Vector2(3.50, 2.62),
    ))

    // Rim bead: rolled over the top, outside edge to inside edge
    profile.add(new CubicBezierCurve(
      new Vector2(3.50, 2.62),
      new Vector2(3.50, 2.86),
      new Vector2(3.26, 2.86),
      new Vector2(3.26, 2.62),
    ))

    // Inside wall: near vertical at the rim, shallow as it meets the floor
    profile.add(new CubicBezierCurve(
      new Vector2(3.26, 2.62),
      new Vector2(2.95, 1.70),
      new Vector2(2.75, 0.72),
      new Vector2(2.00, 0.50),
    ))

    // Inside base: eases out of the wall and flattens under the dice
    profile.add(new QuadraticBezierCurve(
      new Vector2(2.00, 0.50),
      new Vector2(1.55, 0.35),
      new Vector2(0.00, 0.35),
    ))

    return profile.getPoints(BOWL_PROFILE_DIVISIONS)
  }
}
